//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mantis_tests.Mantis
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://futureware.biz/mantisconnect", ConfigurationName="mantis_tests.Mantis.MantisConnectPortType")]
    public interface MantisConnectPortType
    {
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_version();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_versionAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_login();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_loginAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_status();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_statusAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_priorities();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_prioritiesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_severities();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_severitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_reproducibilities();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_reproducibilitiesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_projections();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_projectionsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_etas();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_etasAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_resolutions();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_resolutionsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_access_levels();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_access_levelsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_project_status();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_project_statusAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_project_view_states();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_project_view_statesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_view_states();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_view_statesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_custom_field_types();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_custom_field_typesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_get();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_enum_getAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_exists();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_existsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_get();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_getAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issues_get();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issues_getAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issues_get_header();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issues_get_headerAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_get_history();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_get_historyAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_get_biggest_id();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_get_biggest_idAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_get_id_from_summary();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_get_id_from_summaryAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_add();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_addAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_update();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_updateAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_set_tags();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_set_tagsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_delete();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_deleteAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_note_add();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_note_addAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_note_delete();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_note_deleteAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_note_update();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_note_updateAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_relationship_add();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_relationship_addAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_relationship_delete();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_relationship_deleteAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_attachment_add();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_attachment_addAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_attachment_delete();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_attachment_deleteAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_attachment_get();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_attachment_getAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_add();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_addAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_delete();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_deleteAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_update();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_updateAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_id_from_name();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_id_from_nameAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_issues_for_user();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_issues_for_userAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_issues();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_issuesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_issue_headers();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_issue_headersAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_users();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_usersAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_projects_get_user_accessible();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_projects_get_user_accessibleAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_categories();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_categoriesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_add_category();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_add_categoryAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_delete_category();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_delete_categoryAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_rename_category_by_name();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_rename_category_by_nameAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_versions();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_versionsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_version_add();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_version_addAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_version_update();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_version_updateAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_version_delete();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_version_deleteAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_released_versions();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_released_versionsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_unreleased_versions();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_unreleased_versionsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_attachments();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_attachmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_custom_fields();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_custom_fieldsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_attachment_get();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_attachment_getAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_attachment_add();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_attachment_addAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_attachment_delete();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_attachment_deleteAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_all_subprojects();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_project_get_all_subprojectsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_get();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_getAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_get_issues();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_get_issuesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_get_issue_headers();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_get_issue_headersAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_search_issue_headers();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_search_issue_headersAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_search_issues();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_search_issuesAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_search_issue_ids();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_filter_search_issue_idsAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_config_get_string();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_config_get_stringAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_checkin();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_issue_checkinAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_user_pref_get_pref();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_user_pref_get_prefAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_user_profiles_get_all();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_user_profiles_get_allAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_tag_get_all();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_tag_get_allAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_tag_add();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_tag_addAsync();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_tag_delete();
        
        [System.ServiceModel.OperationContractAttribute()]
        void mc_tag_deleteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MantisConnectPortTypeChannel : mantis_tests.Mantis.MantisConnectPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MantisConnectPortTypeClient : System.ServiceModel.ClientBase<mantis_tests.Mantis.MantisConnectPortType>, mantis_tests.Mantis.MantisConnectPortType
    {
        
        public MantisConnectPortTypeClient()
        {
        }
        
        public MantisConnectPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MantisConnectPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MantisConnectPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MantisConnectPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void mc_version()
        {
            base.Channel.mc_version();
        }
        
        public void mc_versionAsync()
        {
            base.Channel.mc_versionAsync();
        }
        
        public void mc_login()
        {
            base.Channel.mc_login();
        }
        
        public void mc_loginAsync()
        {
            base.Channel.mc_loginAsync();
        }
        
        public void mc_enum_status()
        {
            base.Channel.mc_enum_status();
        }
        
        public void mc_enum_statusAsync()
        {
            base.Channel.mc_enum_statusAsync();
        }
        
        public void mc_enum_priorities()
        {
            base.Channel.mc_enum_priorities();
        }
        
        public void mc_enum_prioritiesAsync()
        {
            base.Channel.mc_enum_prioritiesAsync();
        }
        
        public void mc_enum_severities()
        {
            base.Channel.mc_enum_severities();
        }
        
        public void mc_enum_severitiesAsync()
        {
            base.Channel.mc_enum_severitiesAsync();
        }
        
        public void mc_enum_reproducibilities()
        {
            base.Channel.mc_enum_reproducibilities();
        }
        
        public void mc_enum_reproducibilitiesAsync()
        {
            base.Channel.mc_enum_reproducibilitiesAsync();
        }
        
        public void mc_enum_projections()
        {
            base.Channel.mc_enum_projections();
        }
        
        public void mc_enum_projectionsAsync()
        {
            base.Channel.mc_enum_projectionsAsync();
        }
        
        public void mc_enum_etas()
        {
            base.Channel.mc_enum_etas();
        }
        
        public void mc_enum_etasAsync()
        {
            base.Channel.mc_enum_etasAsync();
        }
        
        public void mc_enum_resolutions()
        {
            base.Channel.mc_enum_resolutions();
        }
        
        public void mc_enum_resolutionsAsync()
        {
            base.Channel.mc_enum_resolutionsAsync();
        }
        
        public void mc_enum_access_levels()
        {
            base.Channel.mc_enum_access_levels();
        }
        
        public void mc_enum_access_levelsAsync()
        {
            base.Channel.mc_enum_access_levelsAsync();
        }
        
        public void mc_enum_project_status()
        {
            base.Channel.mc_enum_project_status();
        }
        
        public void mc_enum_project_statusAsync()
        {
            base.Channel.mc_enum_project_statusAsync();
        }
        
        public void mc_enum_project_view_states()
        {
            base.Channel.mc_enum_project_view_states();
        }
        
        public void mc_enum_project_view_statesAsync()
        {
            base.Channel.mc_enum_project_view_statesAsync();
        }
        
        public void mc_enum_view_states()
        {
            base.Channel.mc_enum_view_states();
        }
        
        public void mc_enum_view_statesAsync()
        {
            base.Channel.mc_enum_view_statesAsync();
        }
        
        public void mc_enum_custom_field_types()
        {
            base.Channel.mc_enum_custom_field_types();
        }
        
        public void mc_enum_custom_field_typesAsync()
        {
            base.Channel.mc_enum_custom_field_typesAsync();
        }
        
        public void mc_enum_get()
        {
            base.Channel.mc_enum_get();
        }
        
        public void mc_enum_getAsync()
        {
            base.Channel.mc_enum_getAsync();
        }
        
        public void mc_issue_exists()
        {
            base.Channel.mc_issue_exists();
        }
        
        public void mc_issue_existsAsync()
        {
            base.Channel.mc_issue_existsAsync();
        }
        
        public void mc_issue_get()
        {
            base.Channel.mc_issue_get();
        }
        
        public void mc_issue_getAsync()
        {
            base.Channel.mc_issue_getAsync();
        }
        
        public void mc_issues_get()
        {
            base.Channel.mc_issues_get();
        }
        
        public void mc_issues_getAsync()
        {
            base.Channel.mc_issues_getAsync();
        }
        
        public void mc_issues_get_header()
        {
            base.Channel.mc_issues_get_header();
        }
        
        public void mc_issues_get_headerAsync()
        {
            base.Channel.mc_issues_get_headerAsync();
        }
        
        public void mc_issue_get_history()
        {
            base.Channel.mc_issue_get_history();
        }
        
        public void mc_issue_get_historyAsync()
        {
            base.Channel.mc_issue_get_historyAsync();
        }
        
        public void mc_issue_get_biggest_id()
        {
            base.Channel.mc_issue_get_biggest_id();
        }
        
        public void mc_issue_get_biggest_idAsync()
        {
            base.Channel.mc_issue_get_biggest_idAsync();
        }
        
        public void mc_issue_get_id_from_summary()
        {
            base.Channel.mc_issue_get_id_from_summary();
        }
        
        public void mc_issue_get_id_from_summaryAsync()
        {
            base.Channel.mc_issue_get_id_from_summaryAsync();
        }
        
        public void mc_issue_add()
        {
            base.Channel.mc_issue_add();
        }
        
        public void mc_issue_addAsync()
        {
            base.Channel.mc_issue_addAsync();
        }
        
        public void mc_issue_update()
        {
            base.Channel.mc_issue_update();
        }
        
        public void mc_issue_updateAsync()
        {
            base.Channel.mc_issue_updateAsync();
        }
        
        public void mc_issue_set_tags()
        {
            base.Channel.mc_issue_set_tags();
        }
        
        public void mc_issue_set_tagsAsync()
        {
            base.Channel.mc_issue_set_tagsAsync();
        }
        
        public void mc_issue_delete()
        {
            base.Channel.mc_issue_delete();
        }
        
        public void mc_issue_deleteAsync()
        {
            base.Channel.mc_issue_deleteAsync();
        }
        
        public void mc_issue_note_add()
        {
            base.Channel.mc_issue_note_add();
        }
        
        public void mc_issue_note_addAsync()
        {
            base.Channel.mc_issue_note_addAsync();
        }
        
        public void mc_issue_note_delete()
        {
            base.Channel.mc_issue_note_delete();
        }
        
        public void mc_issue_note_deleteAsync()
        {
            base.Channel.mc_issue_note_deleteAsync();
        }
        
        public void mc_issue_note_update()
        {
            base.Channel.mc_issue_note_update();
        }
        
        public void mc_issue_note_updateAsync()
        {
            base.Channel.mc_issue_note_updateAsync();
        }
        
        public void mc_issue_relationship_add()
        {
            base.Channel.mc_issue_relationship_add();
        }
        
        public void mc_issue_relationship_addAsync()
        {
            base.Channel.mc_issue_relationship_addAsync();
        }
        
        public void mc_issue_relationship_delete()
        {
            base.Channel.mc_issue_relationship_delete();
        }
        
        public void mc_issue_relationship_deleteAsync()
        {
            base.Channel.mc_issue_relationship_deleteAsync();
        }
        
        public void mc_issue_attachment_add()
        {
            base.Channel.mc_issue_attachment_add();
        }
        
        public void mc_issue_attachment_addAsync()
        {
            base.Channel.mc_issue_attachment_addAsync();
        }
        
        public void mc_issue_attachment_delete()
        {
            base.Channel.mc_issue_attachment_delete();
        }
        
        public void mc_issue_attachment_deleteAsync()
        {
            base.Channel.mc_issue_attachment_deleteAsync();
        }
        
        public void mc_issue_attachment_get()
        {
            base.Channel.mc_issue_attachment_get();
        }
        
        public void mc_issue_attachment_getAsync()
        {
            base.Channel.mc_issue_attachment_getAsync();
        }
        
        public void mc_project_add()
        {
            base.Channel.mc_project_add();
        }
        
        public void mc_project_addAsync()
        {
            base.Channel.mc_project_addAsync();
        }
        
        public void mc_project_delete()
        {
            base.Channel.mc_project_delete();
        }
        
        public void mc_project_deleteAsync()
        {
            base.Channel.mc_project_deleteAsync();
        }
        
        public void mc_project_update()
        {
            base.Channel.mc_project_update();
        }
        
        public void mc_project_updateAsync()
        {
            base.Channel.mc_project_updateAsync();
        }
        
        public void mc_project_get_id_from_name()
        {
            base.Channel.mc_project_get_id_from_name();
        }
        
        public void mc_project_get_id_from_nameAsync()
        {
            base.Channel.mc_project_get_id_from_nameAsync();
        }
        
        public void mc_project_get_issues_for_user()
        {
            base.Channel.mc_project_get_issues_for_user();
        }
        
        public void mc_project_get_issues_for_userAsync()
        {
            base.Channel.mc_project_get_issues_for_userAsync();
        }
        
        public void mc_project_get_issues()
        {
            base.Channel.mc_project_get_issues();
        }
        
        public void mc_project_get_issuesAsync()
        {
            base.Channel.mc_project_get_issuesAsync();
        }
        
        public void mc_project_get_issue_headers()
        {
            base.Channel.mc_project_get_issue_headers();
        }
        
        public void mc_project_get_issue_headersAsync()
        {
            base.Channel.mc_project_get_issue_headersAsync();
        }
        
        public void mc_project_get_users()
        {
            base.Channel.mc_project_get_users();
        }
        
        public void mc_project_get_usersAsync()
        {
            base.Channel.mc_project_get_usersAsync();
        }
        
        public void mc_projects_get_user_accessible()
        {
            base.Channel.mc_projects_get_user_accessible();
        }
        
        public void mc_projects_get_user_accessibleAsync()
        {
            base.Channel.mc_projects_get_user_accessibleAsync();
        }
        
        public void mc_project_get_categories()
        {
            base.Channel.mc_project_get_categories();
        }
        
        public void mc_project_get_categoriesAsync()
        {
            base.Channel.mc_project_get_categoriesAsync();
        }
        
        public void mc_project_add_category()
        {
            base.Channel.mc_project_add_category();
        }
        
        public void mc_project_add_categoryAsync()
        {
            base.Channel.mc_project_add_categoryAsync();
        }
        
        public void mc_project_delete_category()
        {
            base.Channel.mc_project_delete_category();
        }
        
        public void mc_project_delete_categoryAsync()
        {
            base.Channel.mc_project_delete_categoryAsync();
        }
        
        public void mc_project_rename_category_by_name()
        {
            base.Channel.mc_project_rename_category_by_name();
        }
        
        public void mc_project_rename_category_by_nameAsync()
        {
            base.Channel.mc_project_rename_category_by_nameAsync();
        }
        
        public void mc_project_get_versions()
        {
            base.Channel.mc_project_get_versions();
        }
        
        public void mc_project_get_versionsAsync()
        {
            base.Channel.mc_project_get_versionsAsync();
        }
        
        public void mc_project_version_add()
        {
            base.Channel.mc_project_version_add();
        }
        
        public void mc_project_version_addAsync()
        {
            base.Channel.mc_project_version_addAsync();
        }
        
        public void mc_project_version_update()
        {
            base.Channel.mc_project_version_update();
        }
        
        public void mc_project_version_updateAsync()
        {
            base.Channel.mc_project_version_updateAsync();
        }
        
        public void mc_project_version_delete()
        {
            base.Channel.mc_project_version_delete();
        }
        
        public void mc_project_version_deleteAsync()
        {
            base.Channel.mc_project_version_deleteAsync();
        }
        
        public void mc_project_get_released_versions()
        {
            base.Channel.mc_project_get_released_versions();
        }
        
        public void mc_project_get_released_versionsAsync()
        {
            base.Channel.mc_project_get_released_versionsAsync();
        }
        
        public void mc_project_get_unreleased_versions()
        {
            base.Channel.mc_project_get_unreleased_versions();
        }
        
        public void mc_project_get_unreleased_versionsAsync()
        {
            base.Channel.mc_project_get_unreleased_versionsAsync();
        }
        
        public void mc_project_get_attachments()
        {
            base.Channel.mc_project_get_attachments();
        }
        
        public void mc_project_get_attachmentsAsync()
        {
            base.Channel.mc_project_get_attachmentsAsync();
        }
        
        public void mc_project_get_custom_fields()
        {
            base.Channel.mc_project_get_custom_fields();
        }
        
        public void mc_project_get_custom_fieldsAsync()
        {
            base.Channel.mc_project_get_custom_fieldsAsync();
        }
        
        public void mc_project_attachment_get()
        {
            base.Channel.mc_project_attachment_get();
        }
        
        public void mc_project_attachment_getAsync()
        {
            base.Channel.mc_project_attachment_getAsync();
        }
        
        public void mc_project_attachment_add()
        {
            base.Channel.mc_project_attachment_add();
        }
        
        public void mc_project_attachment_addAsync()
        {
            base.Channel.mc_project_attachment_addAsync();
        }
        
        public void mc_project_attachment_delete()
        {
            base.Channel.mc_project_attachment_delete();
        }
        
        public void mc_project_attachment_deleteAsync()
        {
            base.Channel.mc_project_attachment_deleteAsync();
        }
        
        public void mc_project_get_all_subprojects()
        {
            base.Channel.mc_project_get_all_subprojects();
        }
        
        public void mc_project_get_all_subprojectsAsync()
        {
            base.Channel.mc_project_get_all_subprojectsAsync();
        }
        
        public void mc_filter_get()
        {
            base.Channel.mc_filter_get();
        }
        
        public void mc_filter_getAsync()
        {
            base.Channel.mc_filter_getAsync();
        }
        
        public void mc_filter_get_issues()
        {
            base.Channel.mc_filter_get_issues();
        }
        
        public void mc_filter_get_issuesAsync()
        {
            base.Channel.mc_filter_get_issuesAsync();
        }
        
        public void mc_filter_get_issue_headers()
        {
            base.Channel.mc_filter_get_issue_headers();
        }
        
        public void mc_filter_get_issue_headersAsync()
        {
            base.Channel.mc_filter_get_issue_headersAsync();
        }
        
        public void mc_filter_search_issue_headers()
        {
            base.Channel.mc_filter_search_issue_headers();
        }
        
        public void mc_filter_search_issue_headersAsync()
        {
            base.Channel.mc_filter_search_issue_headersAsync();
        }
        
        public void mc_filter_search_issues()
        {
            base.Channel.mc_filter_search_issues();
        }
        
        public void mc_filter_search_issuesAsync()
        {
            base.Channel.mc_filter_search_issuesAsync();
        }
        
        public void mc_filter_search_issue_ids()
        {
            base.Channel.mc_filter_search_issue_ids();
        }
        
        public void mc_filter_search_issue_idsAsync()
        {
            base.Channel.mc_filter_search_issue_idsAsync();
        }
        
        public void mc_config_get_string()
        {
            base.Channel.mc_config_get_string();
        }
        
        public void mc_config_get_stringAsync()
        {
            base.Channel.mc_config_get_stringAsync();
        }
        
        public void mc_issue_checkin()
        {
            base.Channel.mc_issue_checkin();
        }
        
        public void mc_issue_checkinAsync()
        {
            base.Channel.mc_issue_checkinAsync();
        }
        
        public void mc_user_pref_get_pref()
        {
            base.Channel.mc_user_pref_get_pref();
        }
        
        public void mc_user_pref_get_prefAsync()
        {
            base.Channel.mc_user_pref_get_prefAsync();
        }
        
        public void mc_user_profiles_get_all()
        {
            base.Channel.mc_user_profiles_get_all();
        }
        
        public void mc_user_profiles_get_allAsync()
        {
            base.Channel.mc_user_profiles_get_allAsync();
        }
        
        public void mc_tag_get_all()
        {
            base.Channel.mc_tag_get_all();
        }
        
        public void mc_tag_get_allAsync()
        {
            base.Channel.mc_tag_get_allAsync();
        }
        
        public void mc_tag_add()
        {
            base.Channel.mc_tag_add();
        }
        
        public void mc_tag_addAsync()
        {
            base.Channel.mc_tag_addAsync();
        }
        
        public void mc_tag_delete()
        {
            base.Channel.mc_tag_delete();
        }
        
        public void mc_tag_deleteAsync()
        {
            base.Channel.mc_tag_deleteAsync();
        }
    }
}
